volumes:
  db-data:
    # name: horus-bot-data
    # external: true

services:
  bot:
    container_name: tu-coche-dana
    image: thal0s/tu-coche-dana:latest
    depends_on:
      - db
    build: ./
    env_file: .env
    #volumes: # - ${CERT_FILE_TLS_MACHINE}:${CERT_FILE_TLS}
    command: bash -c "sleep 1.5 && /bot/start.sh"
    links:
      - "db:database"
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5434:5432
    volumes:
      - db-data:/var/lib/postgres/data
    env_file: .env
